<SpriteLayer@RelativeLayout>:
#    size_hint: (None, None)
    canvas:
        Color:
            rgba: (1.0, 0.0, 0.0, 0.5)
        Rectangle:
            pos: self.pos
            size: self.size


<Anchor>:
    size: (0, 0)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    canvas:
        Color:
            rgba: (0.0, 0.0, 1.0, 1.0)
        Rectangle:
            pos: self.center
            size: (20, 20)